### PR TITLE
Add hide sidebar button for mobile users

### PR DESCRIPTION
**Pull request by gidoBOSSftw5731**

### CODE REVIEW

**Comment by asineth0** [comment]
We use TailwindCSS, which has breakpoints..

**Comment by gidoBOSSftw5731** [comment]
I don't really think those would help much but it wouldn't be hard to move to them and tweak the UI slightly, I know that long-term the plan is to make an entirely separate mobile UI but this is far enough down it seems reasonable to add atleast a little bit of support

**Comment by gidoBOSSftw5731** [comment]
@asineth0 happy?

**Comment by A-A-Rush-INC** [comment]
As a member of gido's idiot-testing monkEs this would be real helpful as a stopgap.

**Comment by asineth0** [comment]
Added in f966e2e.

**Pull request closed without merging**
