### PR TITLE
Adjust spacing between message

### PR DESCRIPTION
**Pull request by gidoBOSSftw5731**
originally proposed in #48

### CODE REVIEW

**Comment by gidoBOSSftw5731** [comment]
Seems to be a bug, will send in commit to fix momentarily (tailwindcss is weird)

**Comment by gidoBOSSftw5731** [comment]
Screenshot from 2021-04-14 14-47-23
Updated spacing to use these rules:
If the last message was less than 30 minutes ago and from the same person, lessen padding
If it was over 30 minutes ago or from someone else, add padding

Avatars also follow a similar rule.

**Comment by gidoBOSSftw5731** [comment]
Screenshot from 2021-04-14 15-05-16
same rules as before but the spacing was partially reduced

**Comment by A-A-Rush-INC** [comment]
Splitting after 30 minutes (as gido's done here) would be much appreciated.

**Comment by asineth0** [comment]
Added in 889eae2. Although, I changed the threshold for messages being "recent" to 15m and made the computed properties a bit clearer/easier to understand.

**Pull request closed without merging**
