### PR TITLE
Add .5rem of spacing when the sender changes and remove space when sender is same

### PR DESCRIPTION
**Pull request by gidoBOSSftw5731**
This has been idiot-tested by 4 testers and this was the one option that was not too large and also liked by all of them. It makes reading messages with many people going back and fourth much easier.

### CODE REVIEW

**Comment by oopsie1412** [comment]
yes

**Comment by pwncyber** [comment]
**_### As one of the idiot testers I concur with this statement._**

**Comment by oopsie1412** [comment]
**_this idiot is in agreement_**

**Comment by gidoBOSSftw5731** [comment]
Screenshot from 2021-04-14 12-24-15
@asineth0 example

**Comment by asineth0** [comment]
Added in 77b73c4.

**Pull request closed without merging**
